### ISSUE TITLE
Update response.sh and csd.sh with $dwi

### ISSUE THREAD

**Issue by finnlennartsson** [HIIM-PERINEDO/zagreb_dhcp#35]
Tag **response** and **csd** with which **dwi** has been used to generate it.

This is relevant when we want to distinguish 
- "dwinormalise individual" =>{dwi}_inorm.mif.gz
from
- "dwinormalise group" =>{dwi}_gnorm.mif.gz

In each file, do like this
```
dwibase=`basename $dwi .mif.gz` 
...
and then replace `${response}_` with $`{response}_${dwibase}_` in dMRI/response.sh and dMRI/csd.sh
```

**Comment by Dlasic7** [comment]
Updated response and csd script as well as the default file pointers in downstream scripts(registration.sh).
